// Generates the machine-readable schema artifacts from the zod source of truth
// (src/schema.ts). zod is the ergonomic dev surface; these emitted files are the
// committed cross-language contract:
//
//   schema/disclosure.schema.json        - JSON Schema 2020-12 for the disclosure document
//   schema/signed-disclosure.schema.json - the v1 object envelope
//   schema/jws-signed-disclosure.schema.json - the v2 flattened-JWS envelope
//   schema/constraints.json              - the normalized enum/literal/pattern grammar that
//                                          the native verifiers (go/python/rust/c) load, so
//                                          the field grammar is defined ONCE, not hand-copied
//                                          into five languages.
//
// `conformance/schema-drift.test.ts` regenerates these in-memory and fails CI if the
// committed files drift from the zod source. Regenerate after a schema change:
//   node --import tsx scripts/generate-schema.ts

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { argv } from "node:process";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import {
  AgentDisclosureSchema,
  ATTESTATION_LEVELS,
  CONSTRAINT_KINDS,
  CUSTODY_MODES,
  DIGEST_ALGORITHM,
  DISCLOSURE_SCHEMA_VERSION,
  JwsSignedDisclosureSchema,
  KNOWN_ATTESTATION_SCHEMES,
  MANDATE_PERIODS,
  REDTEAM_GRADES,
  REVERSE_DOMAIN_PATTERN,
  SignedDisclosureSchema,
  TOOL_ACCESS_LEVELS,
} from "../src/schema.ts";

// biome-ignore lint/suspicious/noExplicitAny: zod's toJSONSchema typing varies by minor version
const toJsonSchema = (schema: unknown) => (z as any).toJSONSchema(schema, { target: "draft-2020-12" });

/** The normalized grammar manifest the native verifiers consume. Mirrors the exported
 *  enum consts in src/schema.ts exactly (that is the single source). */
export function buildConstraints() {
  return {
    _comment:
      "Generated by scripts/generate-schema.ts from src/schema.ts - the single cross-language source of the disclosure field grammar. Native verifiers load this to validate enums/literals; DO NOT hand-edit. conformance/schema-drift.test.ts fails CI on drift.",
    version: DISCLOSURE_SCHEMA_VERSION,
    digestAlgorithm: DIGEST_ALGORITHM,
    custody: [...CUSTODY_MODES],
    attestationLevel: [...ATTESTATION_LEVELS],
    attestationSchemeKnown: [...KNOWN_ATTESTATION_SCHEMES],
    attestationSchemeReverseDomainPattern: REVERSE_DOMAIN_PATTERN,
    constraintKind: [...CONSTRAINT_KINDS],
    toolAccess: [...TOOL_ACCESS_LEVELS],
    mandatePeriod: [...MANDATE_PERIODS],
    redTeamGrade: [...REDTEAM_GRADES],
  };
}

/** All artifacts as { relativePath -> serialized content }. Pure, so the drift test can
 *  compare these against the committed files without writing anything. */
export function buildArtifacts(): Record<string, string> {
  const ser = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
  return {
    "schema/disclosure.schema.json": ser(toJsonSchema(AgentDisclosureSchema)),
    "schema/signed-disclosure.schema.json": ser(toJsonSchema(SignedDisclosureSchema)),
    "schema/jws-signed-disclosure.schema.json": ser(toJsonSchema(JwsSignedDisclosureSchema)),
    "schema/constraints.json": ser(buildConstraints()),
  };
}

function main() {
  const root = new URL("..", import.meta.url);
  const artifacts = buildArtifacts();
  for (const [rel, content] of Object.entries(artifacts)) {
    writeFileSync(fileURLToPath(new URL(rel, root)), content);
  }
  console.log(`wrote ${Object.keys(artifacts).length} schema artifacts:\n  ${Object.keys(artifacts).join("\n  ")}`);
}

// Run as a script (write files); stay inert when imported by the drift test.
if (argv[1] && resolve(argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
